# Generated by Django 4.2.8 on 2023-12-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='rol',
            field=models.CharField(default='default', max_length=10),
        ),
    ]
